# Generated by Django 5.1.2 on 2024-11-07 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('idBarang', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('harga', models.PositiveIntegerField(verbose_name='harga')),
            ],
        ),
        migrations.CreateModel(
            name='pembeli',
            fields=[
                ('id_pembeli', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membeli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_harga', models.PositiveIntegerField(verbose_name='total_harga')),
                ('idBarang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informasi.barang')),
                ('id_pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informasi.pembeli')),
            ],
        ),
    ]
