# Generated by Django 5.1.2 on 2024-11-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name_plural': 'Barang'},
        ),
    ]
