# Generated by Django 5.1.2 on 2024-11-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0004_membeli_tanggal_pembelian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name': 'Barang', 'verbose_name_plural': 'Barang'},
        ),
        migrations.AlterModelOptions(
            name='membeli',
            options={'verbose_name': 'Membeli', 'verbose_name_plural': 'Membeli'},
        ),
    ]
